name: Compile LaTeX document

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full

    - name: Compile LaTeX document
      run: |
        pdflatex main.tex

    - name: Upload compiled PDF
      uses: actions/upload-artifact@v2
      with:
        name: document
        path: main.pdf
