name: Compile LaTeX document

on: [push, pull_request]

permissions:
  contents: write  # Explicitly grant write permissions to the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full

    - name: Copy Quiver package
      run: |
        sudo mkdir -p /usr/share/texlive/texmf-dist/tex/latex/quiver
        sudo cp quiver.sty /usr/share/texlive/texmf-dist/tex/latex/quiver/
        sudo texhash

    - name: Compile LaTeX document
      run: |
        pdflatex main.tex

    - name: Move compiled PDF to root directory and create .nojekyll file
      run: |
        mv main.pdf index.pdf
        touch .nojekyll

    - name: Commit and push the PDF to main branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add index.pdf .nojekyll
        git commit -m "Publish compiled PDF to root directory"
        git push origin main
