name: Compile LaTeX document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create .nojekyll file
      run: |
        touch .nojekyll

    - name: Commit .nojekyll file
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .nojekyll
        git commit -m "Add .nojekyll file to disable Jekyll"
        git push origin main

    - name: Set up TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full
        sudo apt-get install -y texlive-latex-extra texlive-science texlive-publishers

    - name: Compile LaTeX document
      run: |
        pdflatex main.tex

    - name: Move compiled PDF to root directory
      run: |
        mv main.pdf index.pdf

    - name: Commit and push the PDF to main branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add index.pdf
        git commit -m "Publish compiled PDF to root directory"
        git push origin main
